name: Run Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0' # or any other version you prefer

      - name: Install dependencies
        run: npm ci

      - name: Print Environment Variables
        run: |
          echo "USERNAME: $USERNAME"
          echo "PASSWORD: $PASSWORD"
          echo "NAGA_API_KEY: $NAGA_API_KEY"
          
      - name: Run script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NAGA_API_KEY: ${{ secrets.NAGA_API_KEY }}
        run: node script.js



        